project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: Metill
  site-url: metill.is
  search: false
  navbar: false
        
format:
  html:
    include-in-header: header/header.html
    theme: [flatly, theme.scss]
    css: style.css
    execute: 
      freeze: true
      cache: true

editor: source

