project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: Metill
  search: false
  navbar: 
    collapse: false
    right:
      - text: "Greinar"
        href: posts.qmd
      - text: "Um Metil"
        href: about.qmd
        
format:
  html:
    theme: [paper, theme.scss]
    css: style.css

editor: source

